/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.sunrisedentalclinic.view;

/**
 *
 * @author Lenovo
 */
public class LoginFrame extends javax.swing.JFrame {

    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
        setupLoginInterface();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
private void setupLoginInterface() {

    setTitle("Sunrise Dental Clinic - Login");
    setSize(500, 400);
    setLocationRelativeTo(null);
    setResizable(false);

    getContentPane().setBackground(
            new java.awt.Color(225, 245, 254)
    );

    javax.swing.JLabel lblTitle =
            new javax.swing.JLabel(
                    "SUNRISE DENTAL CLINIC",
                    javax.swing.SwingConstants.CENTER
            );

    lblTitle.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    24
            )
    );

    lblTitle.setForeground(
            new java.awt.Color(0, 105, 148)
    );

    javax.swing.JLabel lblUsername =
            new javax.swing.JLabel("Username:");

    javax.swing.JLabel lblPassword =
            new javax.swing.JLabel("Password:");

    javax.swing.JTextField txtUsername =
            new javax.swing.JTextField();

    javax.swing.JPasswordField txtPassword =
            new javax.swing.JPasswordField();

    javax.swing.JButton btnLogin =
            new javax.swing.JButton("LOGIN");

    javax.swing.JButton btnClear =
            new javax.swing.JButton("CLEAR");

    javax.swing.JPanel panel =
            new javax.swing.JPanel(
                    new java.awt.GridLayout(5, 2, 10, 10)
            );

    panel.setBackground(java.awt.Color.WHITE);

    panel.setBorder(
            javax.swing.BorderFactory.createEmptyBorder(
                    30, 40, 30, 40
            )
    );

    panel.add(lblUsername);
    panel.add(txtUsername);

    panel.add(lblPassword);
    panel.add(txtPassword);

    panel.add(new javax.swing.JLabel(""));
    panel.add(new javax.swing.JLabel(""));

    panel.add(btnLogin);
    panel.add(btnClear);

    getContentPane().setLayout(
            new java.awt.BorderLayout()
    );

    getContentPane().add(
            lblTitle,
            java.awt.BorderLayout.NORTH
    );

    getContentPane().add(
            panel,
            java.awt.BorderLayout.CENTER
    );

    btnClear.addActionListener(e -> {
        txtUsername.setText("");
        txtPassword.setText("");
        txtUsername.requestFocus();
    });

    btnLogin.addActionListener(e -> {

        String username =
                txtUsername.getText().trim();

        String password =
                new String(txtPassword.getPassword());

        if (username.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter your username.",
                    "Login Warning",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        if (password.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter your password.",
                    "Login Warning",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            com.mycompany.sunrisedentalclinic.model.User user =
                    new com.mycompany.sunrisedentalclinic.controller.LoginController()
                            .login(username, password);

            if (user != null) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Login successful!\nWelcome, "
            + user.getFullName() + "!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    // Close Login window
    dispose();

    // Open Main Dashboard
    new MainFrame(user.getFullName()).setVisible(true);

} else {


                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Invalid username or password.",
                        "Login Failed",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

                txtPassword.setText("");
            }

        } catch (java.sql.SQLException ex) {

    ex.printStackTrace();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Database connection error:\n"
            + ex.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

} catch (Exception ex) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred.",
                    "System Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
public static void main(String[] args) {

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new LoginFrame().setVisible(true);
        }
    });
}
}
